---
- name: restart network
  service:
    name: network
    state: restarted

- name: restart sshd
  service:
    name: sshd
    state: restarted

- name: reload sshd
  service:
    name: sshd
    state: reloaded

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: reload firewalld
  command: firewall-cmd --reload

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted