### smart
- name: be sure smartmontools is installed
  yum:
    name: smartmontools
    state: installed
  when:
    - '"redhat" in group_names or "extern" in group_names'
  tags: smartd

- name: update smart db
  shell: "update-smart-drivedb"
  when:
    - '"redhat" in group_names or "extern" in group_names'
  tags: smartd

- name: list disks present in the system
  shell: "smartctl --scan | grep -v '/dev/nvme' | grep -v '/dev/bus/' | awk '{print $1}'"
  register: disks
  when:
    - '"redhat" in group_names or "extern" in group_names'
  tags: smartd

- name: check if disks support SMART
  shell: "smartctl -s on {{ item }} ; smartctl -i {{ item }} | grep -qc 'SMART support is: Enabled'"
  with_items: "{{disks.stdout_lines}}"
  register: smart
  ignore_errors: True
  when:
    - '"tpm" in inventory_hostname'
    - '"smtp-01" in inventory_hostname'
  tags: [ 'never','smart_test' ]

- name: create smartd configuration file
  template:
    src: smartd.conf.j2
    dest: /etc/smartmontools/smartd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart smartd
  when:
    - smart is succeeded
    - '"redhat" in group_names'
  tags: [ 'never','smart_test' ]

- name: be sure smartd is running and enabled
  service:
    name: smartd
    state: started
    enabled: yes
  when:
    - smart is succeeded
    - '"redhat" in group_names'
  tags: [ 'never','smart_test' ]

- name: start short test on drives
  shell: "smartctl -t short {{ item }}"
  with_items: "{{disks.stdout_lines}}"
  when:
    - smart is succeeded
    - '"redhat" in group_names'
  tags: [ 'never','smart_test' ]

### mdadm
- name: be sure that scheduled RAID checks are disabled
  file:
    path: /etc/cron.d/raid-check
    state: absent
  tags: mdadm

- name: check mdadm is installed
  yum:
    name: mdadm
    state: installed
  tags: mdadm

- name: list mdraid present in the system
  shell: "mdadm --detail --scan"
  register: mdadm
  tags: mdadm

- name: configured mdadm
  template:
    src: mdadm.conf.j2
    dest: /etc/mdadm.conf
    owner: root
    group: root
    mode: 0644
  when:
    - mdadm.stdout != ""
  tags: mdadm
