---
- name: ensure that sendmail are not installed
  yum:
    name: sendmail
    state: absent
  when:
    - SMTP_sender is defined
  tags: postfix

- name: ensure that postfix is installed
  package:
    name: postfix,cyrus-sasl,cyrus-sasl-plain,s-nail
    state: installed
  when:
    - SMTP_sender is defined
  tags: postfix

- name: copy config file postfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    mode: 0644
  notify:
    - restart postfix
  when:
    - SMTP_sender is defined
  tags: postfix

- name: copy auth file postfix
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    mode: 0600
  register: postfix
  when:
    - SMTP_sender is defined
  tags: postfix

- name: build postfix sasl if file copied
  shell: "postmap /etc/postfix/sasl_passwd"
  when:
    - postfix is defined and postfix is changed
  tags: postfix

- name: delete auth file
  file:
    path: /etc/postfix/sasl_passwd
    state: absent
  when:
    - postfix is defined and postfix is changed
  tags: postfix

- name: copy header map file
  template:
    src: header_check.j2
    dest: /etc/postfix/header_check
    mode: 0644
  notify:
    - restart postfix
  when:
    - SMTP_sender is defined
  tags: postfix

- name: copy sender map file
  template:
    src: sender_canonical_maps.j2
    dest: /etc/postfix/sender_canonical_maps
    mode: 0644
  notify:
    - restart postfix
  when:
    - SMTP_sender is defined
  tags: postfix

- name: replace aliases
  lineinfile:
    path: /etc/aliases
    regexp: '^root: *'
    line: 'root: heiko.bollert@giata.de'
  notify: rebuild aliases
  when:
    - SMTP_sender is defined
  tags: postfix
  
- name: be sure postfix is running and enabled
  service:
    name: postfix
    state: started
    enabled: yes
  when:
    - SMTP_sender is defined
  tags: postfix
