---
- name: ensure that SW are not installed
  yum:
    name: cockpit,cockpit-bridge
    state: absent
  tags: software

### SW installed
- name: ensure that SW are installed
  yum:
    name: epel-release,parted,logwatch,nano,yum-utils
    state: latest
  tags: software

- name: add known hosts
  blockinfile:
    path: /etc/hosts
    block: |
      192.168.80.1   tec-01.giata.intern tec-01
      192.168.80.2   tec-02.giata.intern tec-02
      192.168.80.3   tec-03.giata.intern tec-03
      192.168.80.10  tec-10.giata.intern tec-10
    marker: "# {mark} ANSIBLE MANAGED USER BLOCK"
  tags: hosts
