---
### SW not installed
- name: ensure that SW are not installed
  yum:
    name: cockpit,cockpit-bridge
    state: absent
  when:
    - '"cockpit" not in group_names'
  tags: software

### SW installed
- name: ensure that SW are installed
  yum:
    name: epel-release,parted,gdisk,logwatch,nano,yum-utils
    state: latest
  tags: software

### cockpit
- name: ensure that cockpit is installed
  yum:
    name: cockpit,cockpit-packagekit,cockpit-storaged,cockpit-bridge,cockpit-ws,cockpit-system
    state: latest
  when: 
   - '"cockpit" in group_names'
  tags: cockpit

- name: be sure cockpit is running and enabled
  service:
    name: cockpit
    state: started
    enabled: yes
  when: 
   - '"cockpit" in group_names'  
  tags: cockpit

### podman
- name: ensure that podman is installed
  yum:
    name: podman,podman-compose,cockpit-podman
    state: latest
  when: 
    - '"podman" in group_names'
    - '"cockpit" in group_names'    
  tags: podman

- name: be sure podman is running and enabled
  service:
    name: podman
    state: started
    enabled: yes
  when: 
    - '"podman" in group_names'
    - '"cockpit" in group_names'  
  tags: podman

### postfix
- name: ensure that sendmail are not installed
  yum:
    name: sendmail
    state: absent
  when:
    - SMTP_sender is defined
    - 'inventory_hostname != "smtp-01"'
    - ansible_distribution_major_version >= "8"
  tags: postfix

- name: ensure that postfix is installed
  package:
    name: postfix,cyrus-sasl,cyrus-sasl-plain,s-nail
    state: installed
  when:
    - SMTP_sender is defined
    - 'inventory_hostname != "smtp-01"'
    - ansible_distribution_major_version >= "8"
  tags: postfix

- name: copy config file postfix
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    mode: 0644
  notify:
    - restart postfix
  when:
    - SMTP_sender is defined
    - 'inventory_hostname != "smtp-01"'
    - ansible_distribution_major_version >= "8"
  tags: postfix

- name: copy auth file postfix
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    mode: 0600
  register: postfix_technik
  when:
    - SMTP_sender is defined
    - SMTP_sender is search("technik@giata.com")
    - 'inventory_hostname != "smtp-01"'
    - ansible_distribution_major_version >= "8"
  tags: postfix

- name: build postfix sasl if file copied
  shell: "postmap /etc/postfix/sasl_passwd"
  when:
    - postfix_technik is defined and postfix_technik is changed
    - 'inventory_hostname != "smtp-01"'
    - ansible_distribution_major_version >= "8"
  tags: postfix

- name: copy header map file
  template:
    src: header_check.j2
    dest: /etc/postfix/header_check
    mode: 0644
  notify:
    - restart postfix
  when:
    - SMTP_sender is defined
    - 'inventory_hostname != "smtp-01"'
    - ansible_distribution_major_version >= "8"
  tags: postfix

- name: copy sender map file
  template:
    src: sender_canonical_maps.j2
    dest: /etc/postfix/sender_canonical_maps
    mode: 0644
  notify:
    - restart postfix
  when:
    - SMTP_sender is defined
    - 'inventory_hostname != "smtp-01"'
    - ansible_distribution_major_version >= "8"
  tags: postfix

- name: replace aliases
  lineinfile:
    path: /etc/aliases
    regexp: '^root: *'
    line: 'root: heiko.bollert@giata.de'
  notify: rebuild aliases
  when:
    - SMTP_sender is defined
    - 'inventory_hostname != "smtp-01"'
    - ansible_distribution_major_version >= "8"
  tags: postfix
  
- name: be sure postfix is running and enabled
  service:
    name: postfix
    state: started
    enabled: yes
  when:
    - SMTP_sender is defined
    - 'inventory_hostname != "smtp-01"'
    - ansible_distribution_major_version >= "8"
  tags: postfix
