---
- name: be sure sshd are installed
  yum:
    name: openssh
    state: latest
  tags: sshd

- name: be sure sshd is configured
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    mode: 0600
    owner: "0"
    group: "0"
    backup: yes
    validate: '/usr/sbin/sshd -T -f %s'
  notify: restart sshd
  tags: sshd

- name: add known user keys
  blockinfile:
    path: /root/.ssh/authorized_keys
    block: |
      ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBADYktHqZhkindoViY4eB3MBYgmfGh1fqoCwvQPu5TDnusrG2kNeJdsveEbC1qOcAHkkjRLRKlUMwFDA1DkuZpRr8gE/UmMlldV9u68L+HAlF4rCM9C2i59xsuaFryoSuXqf6wex//7+3eK1tdEEGspQWVXTqwmFnjGOppLkswdeszEGAA== hbol@giata-tec200
      ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAEBnhwV+zR0nQxGnzcuQiLfp0NQpom8USbx6Bk388zmnG0T4/r1FAyTBiLvkGunos7ZQPkHR4u/mIYMba473MO1SgGLbUKotnD95SgrXFQIrmHCs7WneZrmPlkU3RgebLyaVpWA4NtboTguO0R/h+q1pb4Jm0SLSAsVj95LebLV1IUYow== hbol@giata-tec201
      ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAG7hCViL+H4iGW9yd1ik0YR1/q1IVWN3wkFpqh8XfdK0EJeXgGmG1Z4us36MX81EdInLFbvE5f90416oyW8+GomKQDE8+o2XroCsBeWrNr7fKdVwKLY9Xj+7cL52a8Z17QjHhl9PR7PPe09Bv0UtVS99oMtyChKYVoc2Hw3fV2WSrnjrw== hbol@giata-tec207
      ecdsa-sha2-nistp521 AAAAE2VjZHNhLXNoYTItbmlzdHA1MjEAAAAIbmlzdHA1MjEAAACFBAE6yehfBpHYOKg8Zj2F+8uRTm5arH/VaomxmP7FMQSbbwTB2la/D8QRS9w35IIG5jW4btUW1IVys1eO6qiE6FsdsAFGLmNksMJAF5d/Y+A7kNz1wuEo9CYG+azdd541x7tUSEbGq2Gnw/osigqkfnAxY4HBTFC9aPV3/35wMfbias1QvA== hbollert@giata-208
    marker: "# {mark} ANSIBLE MANAGED USER BLOCK"
  tags: sshd

- name: be sure sshd is running and enabled
  service:
    name: sshd
    state: started
    enabled: yes
  tags: sshd