---
- name: be sure smartmontools is installed
  yum:
    name: smartmontools
    state: installed
  tags: smartd

- name: update smart db
  shell: "update-smart-drivedb"
  tags: smartd

- name: list disks present in the system
  shell: "smartctl --scan | grep -v '/dev/nvme' | grep -v '/dev/bus/' | awk '{print $1}'"
  register: disks
  tags: smartd

- name: check if disks support SMART
  shell: "smartctl -s on {{ item }} ; smartctl -i {{ item }} | grep -qc 'SMART support is: Enabled'"
  with_items: "{{disks.stdout_lines}}"
  register: smart
  ignore_errors: True
  tags: smartd

- name: create smartd configuration file
  template:
    src: smartd.conf.j2
    dest: /etc/smartmontools/smartd.conf
    owner: root
    group: root
    mode: 0644
  notify: restart smartd
  when:
    - smart is succeeded
  tags: smartd

- name: be sure smartd is running and enabled
  service:
    name: smartd
    state: started
    enabled: yes
  when:
    - smart is succeeded
  tags: smartd

- name: start short test on drives
  shell: "smartctl -t short {{ item }}"
  with_items: "{{disks.stdout_lines}}"
  when:
    - smart is succeeded
  tags: smartd
