---
ansible_host: 172.26.80.2
FW_Zone_INT: work
FW_Zone_EXT: dmz
FW_Rules_SSH:
  - { zone: 'work', rule: 'rule family="ipv4" source address="172.26.1.0/24" service name="ssh" log prefix="SSH Access" level="notice"  accept' }
  - { zone: 'work', rule: 'rule family="ipv4" source address="172.26.80.0/24" service name="ssh" log prefix="SSH Access" level="notice"  accept' }
#FW_Rules_INT:
#  - { zone: 'work', rule: 'rule family="ipv4" service name="http" accept' }
#  - { zone: 'work', rule: 'rule family="ipv4" service name="https" accept' }
#FW_Rules_EXT:
#  - { zone: 'dmz', rule: 'rule family="ipv4" service name="http" accept' }
#  - { zone: 'dmz', rule: 'rule family="ipv4" service name="https" accept' }
SMTP_sender: technik@giata.com
