---
- name: upgrade all packages (redhat)
  yum:
    name: '*'
    state: latest 
  register: upgraded_RH
  tags: upgrade

- name: autoremove unused packages (redhat)
  yum:
    autoremove: yes    
  tags: upgrade

### reboot system after update
- name: reboot system, upgrade succeed
  command: /sbin/shutdown -r +1
  async: 0
  poll: 0
  ignore_errors: true
  when:
    - upgraded_RH is succeeded
    - upgraded_RH is changed
  tags: upgrade_reboot

