---
- name: restart network
  service:
    name: network
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: reload firewalld
  command: firewall-cmd --reload
